### PR TITLE
Fixed filtering by ', %, _

### LINKED ISSUE #18: Persistent crash due to unescaped tag filter
In 1.8 (10045), if you create an item with a single quote in the tags, for example "John's Room", it will appear in the filter-by-tag menu, but when you try and filter by that tag name it crashes, and then crashes on start up from then on making it impossible to get back into the app. I haven't yet figured out where the default tag filter is stored to work around it in order to get back into the app.

In 1.8, no attempt appeared to be made to escape the tag name, resulting in a query like this:
```sql
... AND item_tags like '%John's room%' ...
```
and the error "android.database.sqlite.SQLiteException: near "s": syntax error (code 1)"

The problem appears to now be in ShoppingList/src/main/java/org/openintents/shopping/provider/ShoppingProvider.java in ShoppingProvider.query():
```java
                String tagFilter = getListTagsFilter(selectionArgs[0]);
                if (!inSearchMode && !TextUtils.isEmpty(tagFilter)) {
                    qb.appendWhere(" AND items.tags like '%" + tagFilter + "%'");
                }
```
As far as I can tell it still makes no attempt to escape it, nor or in getListTagsFilter().

### PR DESCRIPTION
**Pull request by menasheh**
Fixes #18.

### CODE REVIEW

File: ShoppingList/src/main/java/org/openintents/shopping/provider/ShoppingProvider.java [hunk 1]
```diff
@@ -107,6 +107,14 @@ public boolean onCreate() {
         return true;
     }
 
+    public static String EscapeSQLChars(String trapped) {
```
Comment (friedger) [inline ShoppingList/src/main/java/org/openintents/shopping/provider/ShoppingProvider.java]: should be lower case at the beginning :-)
